Add Regtest mode for Litecoin
rnicoll/altcoinj pull request #20
Opened 2017-06-02 13:18 UTC by mrosseel

Adding the regtest params for Litecoin, useful for dev testing without needing testnet coins.

2017-06-18 10:03 UTC, rnicoll requested changes
Couple of comments, mostly I'd rather not copy chunks of Litecoin code into libdohj as I don't think they're helpful once the code is developed. Other than that, looks good to go, thanks!

2017-06-18 10:03 UTC, rnicoll commented on core/src/test/java/org/libdohj/params/LitecoinRegTestParamsTest.java
> + * @author Ross Nicoll
Can you change the author to yourself please? :)

2017-06-18 10:03 UTC, rnicoll commented on core/src/main/java/org/libdohj/params/LitecoinRegTestParams.java
> +    /* Extract from Litecoin source code, definition of regtest params.
I'm not sure it's a good idea to paste this in here; a link to the commit in Github (i.e. https://github.com/litecoin-project/litecoin/blob/edc66b374ea68107c721062152dd95e6aa037d53/src/chainparams.cpp ) would probably make more sense, as once we have this working the parameters shouldn't change unless the original changes (in which case the copied data is unhelpful).

2017-06-19 07:26 UTC, mrosseel commented on core/src/test/java/org/libdohj/params/LitecoinRegTestParamsTest.java
> + * @author Ross Nicoll
ok

2017-06-19 07:26 UTC, mrosseel commented on core/src/main/java/org/libdohj/params/LitecoinRegTestParams.java
> +    /* Extract from Litecoin source code, definition of regtest params.
yeah np, link is better

2017-06-19 07:40 UTC, mrosseel commented
please recheck, thx

2017-06-19 08:58 UTC, rnicoll approved these changes

2017-06-19 08:58 UTC, merged

2017-06-19 08:58 UTC, rnicoll commented
Many thanks for that!