Namecoin: add LevelDBTransactionCache algorithm.
rnicoll/altcoinj pull request #27
Opened 2017-07-14 22:21 UTC by JeremyRand

This Namecoin name lookup algorithm locally caches the unspent name set using LevelDB; it downloads all headers and the most recent year's full blocks.

2017-07-15 11:57 UTC, rnicoll requested changes
Would like to improve exception handling - I've sketched out some comments, can you tackle them and I'll then go back over and probably raise a PR with some further tweaks. Mostly good to narrow down the exception types being thrown, and avoiding unnecessary try-catching.

2017-07-15 11:57 UTC, rnicoll commented on namecoin/src/main/java/org/libdohj/names/NameLookupLatestLevelDBTransactionCache.java
> +                throw new Exception(e1);
Can you just do `throw e1;` please, and mark this method as throwing `IOException` please? Means it's easier for calling code to break down the different error types that can occur.

2017-07-15 11:57 UTC, rnicoll commented on namecoin/src/main/java/org/libdohj/names/NameLookupLatestLevelDBTransactionCache.java
> +                throw new Exception("Block hash mismatch!");
Please use `VerificationException` instead of plain `Exception`, which means we then don't have to catch and rethrow further up.

2017-07-15 11:57 UTC, rnicoll commented on namecoin/src/main/java/org/libdohj/names/NameLookupLatestLevelDBTransactionCache.java
> +                        continue;
It would be good to have a note for reference on why we're accepting transactions with invalid scripts.

2017-07-15 11:57 UTC, rnicoll commented on namecoin/src/main/java/org/libdohj/names/NameLookupLatestLevelDBTransactionCache.java
> +            throw new Exception("Nonpositive block height; not trustworthy!");
Please use `IllegalArgumentException` instead of plain `Exception`

2017-07-15 11:57 UTC, rnicoll commented on namecoin/src/main/java/org/libdohj/names/NameLookupLatestLevelDBTransactionCache.java
> +            throw new Exception("Block does not yet have 12 confirmations; not trustworthy!");
Please use `VerificationException` instead of plain Exception

2017-07-15 11:57 UTC, rnicoll commented on namecoin/src/main/java/org/libdohj/names/NameLookupLatestLevelDBTransactionCache.java
> +            throw new Exception("Block has expired; not trustworthy!");
Please use `VerificationException` instead of plain Exception

2017-07-15 11:57 UTC, rnicoll commented on namecoin/src/main/java/org/libdohj/names/NameLookupLatestLevelDBTransactionCache.java
> +            throw new Exception(e);
Why catch then wrap and rethrow? Surely this should just be;

`public synchronized void close() throws IOException {`
`    db.close();`
`}`

2017-07-15 11:57 UTC, rnicoll commented on namecoin/src/main/java/org/libdohj/names/NameLookupLatestLevelDBTransactionCache.java
> +            throw new Exception(e);
Same point about re-throwing again

2017-07-18 07:07 UTC, JeremyRand commented
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Ross Nicoll:
> Would like to improve exception handling - I've sketched out some
> comments, can you tackle them and I'll then go back over and
> probably raise a PR with some further tweaks. Mostly good to narrow
> down the exception types being thrown, and avoiding unnecessary
> try-catching.

Thanks for the review.  I think I've made the necessary fixes.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZbbOMAAoJELPy0WV4bWVw7UcP/j9i5ksROinbC9TRi7wqUUmB
QM/P5olcB0EZWJ7uhF9Pyat6mvX/ySTN8N/Z8gaFe9vM4v/1+wyDIcFW4XuHk7S0
fkgL3ELEvy90ful5vbpsTOFVj43mkPTpvkpcYpWj1cCZ0cLL9z5P04LldPtqNFRn
MQBKttt7vQIwoGrihumVF7+iJSH+/N4Y9i/u7avSrloygXs63Iz9OUdSYwFHCz4m
NZiv+Iry8HCjoPfwRbEWIz1kV5OvXuZauTkE5wNX9VGtvv1sithBJtIdCJeJr/rJ
OpyX6z6qlgmR+KQpH4WrDtIKmozJ8BcW3ErTjlS3YvlPtToGzgAlVU3wyGipApo+
FDKnPX3XYTlQYluVc90vtmGONsw/PpzAmi3DX3GWkOFoZf4hpXyuHnROC9Q7Te7e
0TRhKyinGS3YmikK6N3whwOaqOLBO5+z3xzh52qKk6fdHA/wglTMrQROGFC3WWkM
8PVZ4Wg1vS5fefQ2f3iGSqJ2RYLjmYznLVYmaqxasF6hzyk9tW/et0ZltvqUPMUE
HyOz9fpmjlA84kuJztLxvWiO0gTYPFLxI1DGTi23+Hk+0wIK4yiHmpba8Tc08Ljq
yEYqni0h+7RBTlMpgNm/ZdzXUZaRMF3YuAiUgog4L6O88lULWE+P8HyxYJZLOWi/
85fC1K88xFtNTjHaa1vW
=0Q94
-----END PGP SIGNATURE-----

2017-11-04 21:51 UTC, JeremyRand commented
@rnicoll is anything else needed on my end for this?

2017-11-06 10:35 UTC, rnicoll commented
Oops, sorry, missed that coming back, will merge now

2017-11-06 10:36 UTC, merged